//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 11:58:26 AM GMT 
//


package examples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Lending complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Lending">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lendID " type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="periodOfStay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateOfStart" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="dateOfEnd" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="customername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Lending", propOrder = {
    "lendID0020",
    "customerID",
    "periodOfStay",
    "dateOfStart",
    "dateOfEnd",
    "customername",
    "hotelID"
})
public class Lending {

    @XmlElement(name = "lendID ", required = true)
    protected String lendID0020;
    @XmlElement(required = true)
    protected String customerID;
    @XmlElement(required = true)
    protected String periodOfStay;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfStart;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateOfEnd;
    @XmlElement(required = true)
    protected String customername;
    @XmlElement(required = true)
    protected String hotelID;

    /**
     * Gets the value of the lendID0020 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLendID_0020() {
        return lendID0020;
    }

    /**
     * Sets the value of the lendID0020 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLendID_0020(String value) {
        this.lendID0020 = value;
    }

    
    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLendedcustomername() {
        return customername;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLendedcustomername(String value) {
        this.customername = value;
    }
    
    

    /**
     * Gets the value of the periodOfStay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getperiodOfStay() {
        return periodOfStay;
    }

    /**
     * Sets the value of the periodOfStay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setperiodOfStay(String value) {
        this.periodOfStay = value;
    }
    
    

    /**
     * Gets the value of the dateOfStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfStart() {
        return dateOfStart;
    }

    /**
     * Sets the value of the dateOfStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    
    public void setDateOfStart(XMLGregorianCalendar value) {
        this.dateOfStart = value;
    }
    
    

    /**
     * Gets the value of the dateOfEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfEnd() {
        return dateOfEnd;
    }

    /**
     * Sets the value of the dateOfEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfEnd(XMLGregorianCalendar value) {
        this.dateOfEnd = value;
    }

    
    
    /**
     * Gets the value of the hotelRentalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String gethotelRentalID() {
        return customername;
    }

    /**
     * Sets the value of the hotelRentalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void sethotelRentalID(String value) {
        this.customername = value;
    }
    
    
    
    /**
     * Gets the value of the hotelRentalID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String gethotelID() {
        return hotelID;
    }

    /**
     * Sets the value of the hotelRentalID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void sethotelID(String value) {
        this.hotelID = value;
    }

}
