//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.26 at 11:58:26 AM GMT 
//


package examples;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Payment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hoteldNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="expiryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="securityCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="hoteldType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payment", propOrder = {
    "hoteldNo",
    "expiryDate",
    "securityCode",
    "hoteldType"
})
public class Payment {

    protected int hoteldNo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expiryDate;
    protected int securityCode;
    @XmlElement(required = true)
    protected String hoteldType;

    /**
     * Gets the value of the hoteldNo property.
     * 
     */
    public int gethoteldNo() {
        return hoteldNo;
    }

    /**
     * Sets the value of the hoteldNo property.
     * 
     */
    public void sethoteldNo(int value) {
        this.hoteldNo = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the securityCode property.
     * 
     */
    public int getSecurityCode() {
        return securityCode;
    }

    /**
     * Sets the value of the securityCode property.
     * 
     */
    public void setSecurityCode(int value) {
        this.securityCode = value;
    }

    /**
     * Gets the value of the hoteldType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String gethoteldType() {
        return hoteldType;
    }

    /**
     * Sets the value of the hoteldType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void sethoteldType(String value) {
        this.hoteldType = value;
    }

}
